tools:
  - class_name: "verl.tools.image_bbox_tool.ImageBBoxTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "image_bbox_tool"
        description: "Draws a bounding box on a specific region of an image based on a bounding box (bbox) and an optional object label."
        parameters:
          type: "object"  
          properties:
            bbox_2d:
              type: "array"
              items:
                type: "number"
              minItems: 4
              maxItems: 4
              description: "The bounding box of the region to draw, as [x1, y1, x2, y2], where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner."
            label:
              type: "string"
              description: "The name or label of the object in the specified bounding box (optional)."
          required: ["bbox_2d"]
  - class_name: "verl.tools.image_crop_tool.ImageCropTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "image_crop_tool"
        description: "Crop a specific region of an image based on a bounding box (bbox) and an optional object label."
        parameters:
          type: "object"  
          properties:
            bbox_2d:
              type: "array"
              items:
                type: "number"
              minItems: 4
              maxItems: 4
              description: "The bounding box of the region to crop, as [x1, y1, x2, y2], where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner."
            label:
              type: "string"
              description: "The name or label of the object in the specified bounding box (optional)."
          required: ["bbox_2d"]
  - class_name: "verl.tools.image_flip_tool.ImageFlipTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "image_flip_tool"
        description: "Flip an image horizontally or vertically."
        parameters:
          type: "object"  
          properties:
            direction:
              type: "string"
              enum: ["horizontal", "vertical"]
              description: "The direction in which to flip the image."
          required: ["direction"]
  - class_name: "verl.tools.image_line_tool.ImageLineTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "image_line_tool"
        description: "Draws a line on a specific region of an image based on start and end coordinates."
        parameters:
          type: "object"  
          properties:
            start:
              type: "array"
              items:
                type: "number"
              minItems: 2
              maxItems: 2
              description: "The starting point of the line, as [x1, y1], where (x1, y1) is the top-left corner."
            end:
              type: "array"
              items:
                type: "number"
              minItems: 2
              maxItems: 2
              description: "The ending point of the line, as [x2, y2], where (x2, y2) is the bottom-right corner."
          required: ["start", "end"]
  - class_name: "verl.tools.image_rotate_tool.ImageRotateTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "image_rotate_tool"
        description: "Rotate an image by a specified angle."
        parameters:
          type: "object"  
          properties:
            angle:
              type: "integer"
              description: "The angle by which to rotate the image, in degrees."
          required: ["angle"]