tools:
  - class_name: "verl.tools.image_bbox_tool.ImageBBoxTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "image_bbox_tool"
        description: "Draws a bounding box on a specific region of an image based on a bounding box (bbox) and an optional object label."
        parameters:
          type: "object"  
          properties:
            bbox_2d:
              type: "array"
              items:
                type: "number"
              minItems: 4
              maxItems: 4
              description: "The bounding box of the region to draw, as [x1, y1, x2, y2], where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner."
            label:
              type: "string"
              description: "The name or label of the object in the specified bounding box (optional)."
          required: ["bbox_2d"]